version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres            # ${DB_DATABASE}
      - POSTGRES_USER=postgres          # ${DB_USERNAME}
      - POSTGRES_PASSWORD=postgres      # ${DB_PASSWORD}
    # - POSTGRES_ROOT_PASSWORD=postgres # ${DB_ROOT_PASSWORD}
    # - POSTGRES_ALLOW_EMPTY_PASSWORD=

    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local

# docker run -v db:/var/lib/postgresql/data -p 5432:5432 -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres postgres:14.1-alpine 
# docker run -p 8080:8080 adminer 